version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16

    working_directory: ~/client

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

deploy:
  machine:
    enabled: true

  working_directory: ~/client

  steps:
    - add_ssh_keys:
        fingerprints:
          - "ff:56:17:0c:0d:4c:cb:2f:8f:09:0b:4f:a3:32:93:2e"
    - checkout
    - run:
        name: Push Master to Production
        command: |
          git push https://https://github.com/meghein/scheduler.git master:production

workflows:
  version: 2
  test:
    jobs:
      - build